/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CenterPanel: typeof import('./src/components/Game/CenterPanel.vue')['default']
    CircularGame: typeof import('./src/components/Game/CircularGame.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    RectangularGame: typeof import('./src/components/Game/RectangularGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seat: typeof import('./src/components/Game/Seat.vue')['default']
    Select: typeof import('primevue/select')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
